<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [2]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greet=greeting(name='Super Man')
print(greet)

print(greeting(name="Super Man"))

Hello Super Man!
Hello Super Man!


In [6]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

print(list_min)
print(list_max)
print(list_mean)

1
5
3.0


### 1.2 Named functions that don’t return

In [8]:

# Your coade here


### 1.3 Anonymous functions

In [9]:
my_short_function = lambda name: f"Hello {name}!"

my_short_function(name="Super Man")

'Hello Super Man!'

In [10]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [11]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [12]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [14]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

greeting()

'Hello no one!'

In [17]:
?print

In [19]:
print('I', 'am', 'Batman!')                 # Just for comparison
print('I', 'am', 'Batman!', sep='---')

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [20]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

return jumps out of the function with the return value. 

If name == 'Batman', then the function will stop and give the value 'Hello Batman!...' (the line of return code outside the if statement does not run).

## Exercise 2 :  Calculator functions

In [9]:
import numpy as np

def add(x,y):
    return x+y

def subtract(x,y):
    return x-y

def multiply(x,y):
    return x*y

def divide(x,y):
    if all(y):
        return x/y
    print("Unable to calculate")

def divide2(x,y):
    ans=np.array([])
    for n,d in zip(x,y):
        if d==0:
            ans=np.append(ans,"NIL")
        else:
            ans=np.append(ans,n/d)
    return ans

x=np.array([36, 34, 44, 76, 27, 6])
y=np.array([64, 66, 56, 24, 73, 0])

In [10]:
add(x,y)

array([100, 100, 100, 100, 100,   6])

In [11]:
subtract(x,y)

array([-28, -32, -12,  52, -46,   6])

In [12]:
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971,    0])

In [13]:
divide(x,y)

Unable to calculate


In [14]:
divide2(x,y)

array(['0.5625', '0.5151515151515151', '0.7857142857142857',
       '3.1666666666666665', '0.3698630136986301', 'NIL'], dtype='<U32')

## Exercise 3 :  max_info() with NumPy

In [15]:
def max_info(numbers):
    np_array=np.array(numbers)
    return np.max(np_array), np.argmax(np_array)

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

max_info(numbers)

(83, 2)