<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [14]:
import numpy as np

py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]

np_array=np.array(py_list)

x = np_array

print(x[0])
print(x[-1])
print(x[0:3])       # 3 - 0 = 3, so 3 values given
print(x[1:6])       # 6 - 1 = 5, so 5 values given
print(x[1:6:2])     # :2 means in steps of two (gives every other value)
print(x[5:])        # len(x) - 5 = 5, so 5 elements (gives to end)
print(x[:5])        # leaving first variable out means 0
print(x[5:2:-1])    # 5 - 2 = 3, so gives 3 values starting from index 5 backwards (-1)
print(x[::-1])      # reverses the list
print(x[::-4])

a1
j10
['a1' 'b2' 'c3']
['b2' 'c3' 'd4' 'e5' 'f6']
['b2' 'd4' 'f6']
['f6' 'g7' 'h8' 'i9' 'j10']
['a1' 'b2' 'c3' 'd4' 'e5']
['f6' 'e5' 'd4']
['j10' 'i9' 'h8' 'g7' 'f6' 'e5' 'd4' 'c3' 'b2' 'a1']
['j10' 'f6' 'b2']


### 1.2 Subsetting by masking (Arrays only)

In [33]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

my_mask = np_array > 3         # change items > 3 to true
print(my_mask)
print(np_array[my_mask])       # overlays np_array with my_mask and print all true values

print(np_array[np_array <= 5])
print(np_array[~(np_array > 3)])                       # '~' means 'NOT'
print(np_array[(np_array > 3) & (np_array < 8)])       # '&' means 'AND'
print(np_array[(np_array < 3) | (np_array > 8)])       # '|' means 'OR'
print(np_array[(np_array >= 6) & ~(np_array == 8)])

[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]
[1 2 3 4 5]
[1 2 3]
[4 5 6 7]
[ 1  2  9 10]
[ 6  7  9 10]


### 1.3 Indexing & Slicing 2D Lists

In [47]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

print(py_list_2d[3])        # What is at position 4 (index 3)?
print(py_list_2d[3][0])     # FIRST element at position 4 (index 3)
print(py_list_2d[:3])
print(py_list_2d[:3][0])
print(py_list_2d[3:6][1])

[4, 'D']
4
[[1, 'A'], [2, 'B'], [3, 'C']]
[1, 'A']
[5, 'E']


### 1.4 Indexing & Slicing 2D Arrays

In [82]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

print(np_array_2d[3])       # What is at position 4 (index 3)?
print(np_array_2d[3, 0])    # FIRST element at position 4 (index 3), use one pair of []
print(np_array_2d[:3])
print(np_array_2d[:3, 1])
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])    # use just : for everything

np_array_2d[0]=[26,"Z"]
np_array_2d

['4' 'D']
4
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]
['A' 'B' 'C']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


array([['26', 'Z'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U11')

### 1.5 Growing lists

In [61]:
x=[1]*10
x

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [62]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [63]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [64]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [65]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [66]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [83]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

# The following will NOT work because cannot change tuple after creation
# a[0] = -1
# a[0] += [10]

1


### 2.2 Be VERY careful when copying

In [85]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [84]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

|Term|Brief description|
|:-|:-|
|Subsetting|Selecting values (_data_) from a list/array|
|Indexing|Retrieving one value (_element_) from the list/array|
|Slicing|Retrieving a range of values (_element_) from the list/array|
|Masking|Filtering a list/array by making use of rules and boolean (_to only show the elements which are __true___)|

## Exercise 2 :  Show me the ‘odd’ letters

In [105]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_numbers = np_array_2d[:,0].astype(int)
print(np_array_numbers)

np_array_odd = np_array_numbers%2
print(np_array_odd)

np_array_mask = np_array_odd == 1
print(np_array_mask)

np_array_2d[np_array_mask,1]

[ 1  3  2  4  5  7  6  8 10  9]
[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [14]:
np_array_2d[(np_array_2d[:,0].astype(int)%2)==1,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [11]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

[x[1] for x in np_array_2d if x[0].astype(int)%2==1]

['A', 'C', 'E', 'G', 'I']